call runDemo concordance RunGoPConcordance X-GoP 1 bible 8
call runDemo concordance RunGoPConcordance X-GoP 2 bible 8
call runDemo concordance RunGoPConcordance X-GoP 4 bible 8
call runDemo concordance RunGoPConcordance X-GoP 8 bible 8
call runDemo concordance RunGoPConcordance X-GoP 16 bible 8
call runDemo concordance RunGoPConcordance X-GoP 32 bible 8
call runDemo concordance RunGoPConcordance X-GoP 64 bible 8
call runDemo concordance RunGoPConcordance X-GoP 1 2bibles 8
call runDemo concordance RunGoPConcordance X-GoP 2 2bibles 8
call runDemo concordance RunGoPConcordance X-GoP 4 2bibles 8
call runDemo concordance RunGoPConcordance X-GoP 8 2bibles 8
call runDemo concordance RunGoPConcordance X-GoP 16 2bibles 8
call runDemo concordance RunGoPConcordance X-GoP 32 2bibles 8
call runDemo concordance RunGoPConcordance X-GoP 64 2bibles 8
call runDemo concordance RunGoPConcordance X-GoP 1 4bibles 8
call runDemo concordance RunGoPConcordance X-GoP 2 4bibles 8
call runDemo concordance RunGoPConcordance X-GoP 4 4bibles 8
call runDemo concordance RunGoPConcordance X-GoP 8 4bibles 8
call runDemo concordance RunGoPConcordance X-GoP 16 4bibles 8
call runDemo concordance RunGoPConcordance X-GoP 32 4bibles 8
call runDemo concordance RunGoPConcordance X-GoP 64 4bibles 8
call runDemo concordance RunGoPConcordance X-GoP 1 bible 16
call runDemo concordance RunGoPConcordance X-GoP 2 bible 16
call runDemo concordance RunGoPConcordance X-GoP 4 bible 16
call runDemo concordance RunGoPConcordance X-GoP 8 bible 16
call runDemo concordance RunGoPConcordance X-GoP 16 bible 16
call runDemo concordance RunGoPConcordance X-GoP 32 bible 16
call runDemo concordance RunGoPConcordance X-GoP 64 bible 16
call runDemo concordance RunGoPConcordance X-GoP 1 2bibles 16
call runDemo concordance RunGoPConcordance X-GoP 2 2bibles 16
call runDemo concordance RunGoPConcordance X-GoP 4 2bibles 16
call runDemo concordance RunGoPConcordance X-GoP 8 2bibles 16
call runDemo concordance RunGoPConcordance X-GoP 16 2bibles 16
call runDemo concordance RunGoPConcordance X-GoP 32 2bibles 16
call runDemo concordance RunGoPConcordance X-GoP 64 2bibles 16
call runDemo concordance RunGoPConcordance X-GoP 1 4bibles 16
call runDemo concordance RunGoPConcordance X-GoP 2 4bibles 16
call runDemo concordance RunGoPConcordance X-GoP 4 4bibles 16
call runDemo concordance RunGoPConcordance X-GoP 8 4bibles 16
call runDemo concordance RunGoPConcordance X-GoP 16 4bibles 16
call runDemo concordance RunGoPConcordance X-GoP 32 4bibles 16
call runDemo concordance RunGoPConcordance X-GoP 64 4bibles 16
call runDemo concordance RunGoPConcordance X-GoP 1 bible 32
call runDemo concordance RunGoPConcordance X-GoP 2 bible 32
call runDemo concordance RunGoPConcordance X-GoP 4 bible 32
call runDemo concordance RunGoPConcordance X-GoP 8 bible 32
call runDemo concordance RunGoPConcordance X-GoP 16 bible 32
call runDemo concordance RunGoPConcordance X-GoP 32 bible 32
call runDemo concordance RunGoPConcordance X-GoP 64 bible 32
call runDemo concordance RunGoPConcordance X-GoP 1 2bibles 32
call runDemo concordance RunGoPConcordance X-GoP 2 2bibles 32
call runDemo concordance RunGoPConcordance X-GoP 4 2bibles 32
call runDemo concordance RunGoPConcordance X-GoP 8 2bibles 32
call runDemo concordance RunGoPConcordance X-GoP 16 2bibles 32
call runDemo concordance RunGoPConcordance X-GoP 32 2bibles 32
call runDemo concordance RunGoPConcordance X-GoP 64 2bibles 32
call runDemo concordance RunGoPConcordance X-GoP 1 4bibles 32
call runDemo concordance RunGoPConcordance X-GoP 2 4bibles 32
call runDemo concordance RunGoPConcordance X-GoP 4 4bibles 32
call runDemo concordance RunGoPConcordance X-GoP 8 4bibles 32
call runDemo concordance RunGoPConcordance X-GoP 16 4bibles 32
call runDemo concordance RunGoPConcordance X-GoP 32 4bibles 32
call runDemo concordance RunGoPConcordance X-GoP 64 4bibles 32
