call runDemo goldbach_Book/scripts ParPrimes Bparprimes 16 1
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 16 2
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 16 4
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 16 8
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 16 16
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 16 32
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 16 64
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 32 1
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 32 2
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 32 4
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 32 8
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 32 16
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 32 32
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 32 64
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 64 1
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 64 2
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 64 4
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 64 8
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 64 16
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 64 32
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 64 64
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 128 1
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 128 2
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 128 4
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 128 8
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 128 16
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 128 32
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 128 64
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 256 1
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 256 2
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 256 4
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 256 8
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 256 16
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 256 32
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 256 64
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 512 1
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 512 2
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 512 4
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 512 8
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 512 16
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 512 32
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 512 64
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 1024 1
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 1024 2
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 1024 4
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 1024 8
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 1024 16
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 1024 32
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 1024 64
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 2048 1
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 2048 2
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 2048 4
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 2048 8
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 2048 16
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 2048 32
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 2048 64
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 4096 1
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 4096 2
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 4096 4
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 4096 8
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 4096 16
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 4096 32
call runDemo goldbach_Book/scripts ParPrimes Bparprimes 4096 64
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 8192 1
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 8192 2
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 8192 4
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 8192 8
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 8192 16
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 8192 32
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 8192 64
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 16384 1
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 16384 2
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 16384 4
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 16384 8
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 16384 16
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 16384 32
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 16384 64
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 32768 1
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 32768 2
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 32768 4
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 32768 8
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 32768 16
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 32768 32
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 32768 64
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 65536 1
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 65536 2
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 65536 4
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 65536 8
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 65536 16
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 65536 32
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 65536 64
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 131072 1
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 131072 2
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 131072 4
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 131072 8
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 131072 16
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 131072 32
call runDemo goldbach_Book/scripts ParPrimes BparPrimes2 131072 64



